### ISSUE TITLE
Getting Doubled Input In Windows

### ISSUE THREAD

**Issue by playdeezgames** [endbasic/endbasic#246] opened 2024-07-30 09:38 UTC
### System Configuration:

Edition	Windows 11 Home
Version	23H2
Installed on	‎9/‎28/‎2022
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0

Using EndBASIC 0.11.0, downloaded fresh from the website.
(I have used both cmd and ps, and I get the same result, and tried two different machines and got the same result)

### Repro Steps:

1. Launch endbasic.exe from command line 
2. Type something, for example `edit`

### Expected:

I'm in the editor

### Actual:

console shows:

`eeddiitt`
(or whatever i typed, but each character is doubled)

### Note:

I did this on my twitch stream. I will amend this issue with a link to the VOD.

I sorta looked for a duplicate issue, but not very well. Apologize if dupe.

**Comment by playdeezgames** [comment] 2024-07-30 13:33
Further note: using the `--console=graphics` flag will not get this behavior.

**Comment by jmmv** [comment] 2024-08-13 21:37
Interesting. I had seen this bug report earlier, but when I tried to reproduce it, I couldn't because I assumed it only happened with the graphics console. So thanks for the clarification that `--console=graphics` makes it go away. I can see the problem now, but I do not know yet why it's happening.

**Comment by jmmv** [comment] 2024-09-14 00:54
Alright, sorry for the delay. I finally had a chance to look into it and the fix is trivial. It should be fixed on master in a moment and I'll try to push a dot release out this weekend.

**Closed** 2024-09-14 00:57 UTC
Labels: bug
