### ISSUE TITLE
Typo in help text, Integral -> integer

### ISSUE THREAD

**Issue by slaurel** [endbasic/endbasic#184] opened 2022-07-26 22:28 UTC
https://github.com/endbasic/endbasic/blob/d7a7c72c5e260ebf304fdd3c8305ce9d47fe5319/cli/tests/repl/help.out#L685

**Comment by jmmv** [comment] 2022-07-27 04:24
Duplicate of #185.

**Closed by jmmv** 2022-07-27 04:24 UTC
